//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 RootLocalFolderId 的本地化字符串。
        /// </summary>
        public static string App_RootLocalFolderId {
            get {
                return ResourceManager.GetString("App_RootLocalFolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Caption_Info {
            get {
                return ResourceManager.GetString("Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件出错 的本地化字符串。
        /// </summary>
        public static string Caption_OpenFileError {
            get {
                return ResourceManager.GetString("Caption_OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性刷新错误 的本地化字符串。
        /// </summary>
        public static string Caption_RefreshError {
            get {
                return ResourceManager.GetString("Caption_RefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap chevron_down_regular_24 {
            get {
                object obj = ResourceManager.GetObject("chevron_down_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap chevron_left_regular_24 {
            get {
                object obj = ResourceManager.GetObject("chevron_left_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap chevron_right_regular_24 {
            get {
                object obj = ResourceManager.GetObject("chevron_right_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap chevron_up_regular_24 {
            get {
                object obj = ResourceManager.GetObject("chevron_up_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap cog_regular_24 {
            get {
                object obj = ResourceManager.GetObject("cog_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap cog_solid_24 {
            get {
                object obj = ResourceManager.GetObject("cog_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap copy_alt_regular_24 {
            get {
                object obj = ResourceManager.GetObject("copy_alt_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap copy_regular_24 {
            get {
                object obj = ResourceManager.GetObject("copy_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap cut_regular_24 {
            get {
                object obj = ResourceManager.GetObject("cut_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap DEFAULT {
            get {
                object obj = ResourceManager.GetObject("DEFAULT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap detail_regular_24 {
            get {
                object obj = ResourceManager.GetObject("detail_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap detail_solid_24 {
            get {
                object obj = ResourceManager.GetObject("detail_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap down_arrow_alt_regular_24 {
            get {
                object obj = ResourceManager.GetObject("down_arrow_alt_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap down_arrow_solid_24 {
            get {
                object obj = ResourceManager.GetObject("down_arrow_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap down_arrow_square_solid_24 {
            get {
                object obj = ResourceManager.GetObject("down_arrow_square_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap explorer {
            get {
                object obj = ResourceManager.GetObject("explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap fileNotFount {
            get {
                object obj = ResourceManager.GetObject("fileNotFount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap left_arrow_alt_regular_24 {
            get {
                object obj = ResourceManager.GetObject("left_arrow_alt_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap left_arrow_solid_24 {
            get {
                object obj = ResourceManager.GetObject("left_arrow_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap left_arrow_square_solid_24 {
            get {
                object obj = ResourceManager.GetObject("left_arrow_square_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap memory_card_regular_24 {
            get {
                object obj = ResourceManager.GetObject("memory_card_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap memory_card_solid_24 {
            get {
                object obj = ResourceManager.GetObject("memory_card_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap menu_regular_24 {
            get {
                object obj = ResourceManager.GetObject("menu_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 参数DbModelBuilder不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_DbModelBuilder {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_DbModelBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数ExplorerProperty不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_ExplorerProperty {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_ExplorerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数ExplorerPropertyList不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_ExplorerPropertyList {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_ExplorerPropertyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数FileInfo不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_FileInfo {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数Files不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_Files {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数Folders不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_Folders {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数Monitor不能为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentNullException_Monitor {
            get {
                return ResourceManager.GetString("Message_ArgumentNullException_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到对应的数据库类型 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentOutOfRangeException_DBType {
            get {
                return ResourceManager.GetString("Message_ArgumentOutOfRangeException_DBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不能为包含以下任何字符： \ / : &quot; ? * &lt; &gt; | 的本地化字符串。
        /// </summary>
        public static string Message_NameCheckError {
            get {
                return ResourceManager.GetString("Message_NameCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名不能为空 的本地化字符串。
        /// </summary>
        public static string Message_NameCheckIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Message_NameCheckIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法粘贴到被剪切的项目里面 的本地化字符串。
        /// </summary>
        public static string Message_PasteError {
            get {
                return ResourceManager.GetString("Message_PasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不存在 的本地化字符串。
        /// </summary>
        public static string Message_PathCheckError {
            get {
                return ResourceManager.GetString("Message_PathCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folders查询结果为NULL 的本地化字符串。
        /// </summary>
        public static string Message_ResultIsNull_Folders {
            get {
                return ResourceManager.GetString("Message_ResultIsNull_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageBoxResult 的本地化字符串。
        /// </summary>
        public static string MessageBoxResult {
            get {
                return ResourceManager.GetString("MessageBoxResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ArgumentOutOfRangeException 的本地化字符串。
        /// </summary>
        public static string Messgae_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Messgae_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap paste_regular_24 {
            get {
                object obj = ResourceManager.GetObject("paste_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap plus_regular_24 {
            get {
                object obj = ResourceManager.GetObject("plus_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap plus_square_solid_24 {
            get {
                object obj = ResourceManager.GetObject("plus_square_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string Property_Type_File {
            get {
                return ResourceManager.GetString("Property_Type_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string Property_Type_Folder {
            get {
                return ResourceManager.GetString("Property_Type_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap right_arrow_alt_regular_24 {
            get {
                object obj = ResourceManager.GetObject("right_arrow_alt_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap right_arrow_solid_24 {
            get {
                object obj = ResourceManager.GetObject("right_arrow_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap right_arrow_square_solid_24 {
            get {
                object obj = ResourceManager.GetObject("right_arrow_square_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap search_alt_2_regular_24 {
            get {
                object obj = ResourceManager.GetObject("search_alt_2_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap search_alt_2_solid_24 {
            get {
                object obj = ResourceManager.GetObject("search_alt_2_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap search_solid_24 {
            get {
                object obj = ResourceManager.GetObject("search_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 数据库在远程计算机或远程服务器中 的本地化字符串。
        /// </summary>
        public static string Settings_IsLocal_False {
            get {
                return ResourceManager.GetString("Settings_IsLocal_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库在当前计算机中 的本地化字符串。
        /// </summary>
        public static string Settings_IsLocal_True {
            get {
                return ResourceManager.GetString("Settings_IsLocal_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap slider_alt_regular_24 {
            get {
                object obj = ResourceManager.GetObject("slider_alt_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap slider_regular_24 {
            get {
                object obj = ResourceManager.GetObject("slider_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap trash_regular_24 {
            get {
                object obj = ResourceManager.GetObject("trash_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap up_arrow_alt_regular_24 {
            get {
                object obj = ResourceManager.GetObject("up_arrow_alt_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap up_arrow_solid_24 {
            get {
                object obj = ResourceManager.GetObject("up_arrow_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap up_arrow_square_solid_24 {
            get {
                object obj = ResourceManager.GetObject("up_arrow_square_solid_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap x_regular_24 {
            get {
                object obj = ResourceManager.GetObject("x_regular_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
