//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileStorageLocation {
            get {
                return ((string)(this["FileStorageLocation"]));
            }
            set {
                this["FileStorageLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsLocal {
            get {
                return ((bool)(this["IsLocal"]));
            }
            set {
                this["IsLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MySQL")]
        public string DBType {
            get {
                return ((string)(this["DBType"]));
            }
            set {
                this["DBType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=127.0.0.1;port=3306;database=FilesExplorerDB;uid=root;password=admin9647;s" +
            "slmode=none;AllowPublicKeyRetrieval=true;")]
        public string ConnectionString4MySQL {
            get {
                return ((string)(this["ConnectionString4MySQL"]));
            }
            set {
                this["ConnectionString4MySQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\HUANG\\DOCUMENTS\\FILES" +
            "EXPLORERINDB.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust" +
            "ServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string ConnectionString4MSSQL {
            get {
                return ((string)(this["ConnectionString4MSSQL"]));
            }
            set {
                this["ConnectionString4MSSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User Id=&quot;dbo&quot;;Password=admin9112;Data Source=(DESCRIPTION=(ADDRESS=(PRO" +
            "TOCOL=tcp)(HOST=192.168.68.240)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl))) ")]
        public string ConnectionString4Oracle {
            get {
                return ((string)(this["ConnectionString4Oracle"]));
            }
            set {
                this["ConnectionString4Oracle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://127.0.0.1:27017")]
        public string ConnectionString4MongoDB {
            get {
                return ((string)(this["ConnectionString4MongoDB"]));
            }
            set {
                this["ConnectionString4MongoDB"] = value;
            }
        }
    }
}
